# Generated by Django 2.1.3 on 2018-11-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.BinaryField(max_length=2096)),
                ('file_location', models.FilePathField(path='/usr/home/ray/projects/dos_game_in_browser/web_site/dos_game')),
                ('image_location', models.FilePathField(null=True, path='/usr/home/ray/projects/dos_game_in_browser/web_site/dos_game')),
                ('download_url', models.URLField()),
                ('executable', models.CharField(max_length=50)),
                ('year', models.DateField(null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('species', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='dos_game.Game')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='dos_game.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(related_name='used_in', to='dos_game.Tag'),
        ),
    ]
