# Generated by Django 2.1.3 on 2018-11-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='year',
        ),
        migrations.AlterField(
            model_name='game',
            name='checksum',
            field=models.BinaryField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='game',
            name='file_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
